DjangoProject/urls.py
from django.contrib import admin
from django.urls import path,include

from django.views.generic import RedirectView
from . import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/dasboard/' ,include(('adminView.urls','adminView'), namespace='adminView')),
    path('', RedirectView.as_view(pattern_name='adminView:index')),
    path('login', views.loginView, name='login'),
    path('logout', views.logoutView, name='logout')

]	

adminView/urls.py
from django.urls import path,re_path

from .views import(DashboardDeleteView,index,login, DashboardUpdateView, DashboardDetailView)
# from .views import IndexViewClass

urlpatterns = [
	path('delete/<int:pk>', DashboardDeleteView.as_view(), name='index_delete'),
	path('update/<int:pk>', DashboardUpdateView.as_view(), name='index_update'),
	path('', index, name='index'),
	# path('create/', DashboardCreateView, name='index_create'),

	path('detail/<int:pk>', DashboardDetailView.as_view(), name='index_detail')
	# path('create', DashboardCreateAndUpdateView.as_view(), name='index_create'),
	# path('', index,name='index'),
]

adminView/models.py
from django.db import models
from .validators import validate_name,validate_description
# Create your models here.

class Hajime(models.Model):
	name 		= models.CharField(max_length=25, null= True, validators=[validate_name])
	description = models.CharField(max_length=100, null= True, validators=[validate_description])

	JURUSAN = (
		('RPL','RPL'),
		('TKJ','TKJ'),
		('MM','MM'),
	)
	majors = models.CharField(max_length=20, choices=JURUSAN, default='RPL')

	def get_absolute_url(self):
		return '/'

	def __str__(self):
		return self.name





adminView/forms.py
from django import forms

from .models import Hajime
# class PostForm(forms.Form):
# 	name = forms.CharField(max_length=25,widget=forms.TextInput(attrs={'class': 'form-control col-6','placeholder':'Full Name'}),required=False)
# 	description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control col-6','rows':3,'placeholder':'Description'}), required=False)

# 	def clean_name(self):
# 		name = self.cleaned_data.get('name')

# 		if name == '':
# 			raise forms.ValidationError('Field Name has required')	

# 		return name


class PostForm(forms.ModelForm):
	class Meta:
		model = Hajime
		fields = [
			'name',
			'description',
			'majors',
		]
		widgets = {
			'name': forms.TextInput(attrs={'class':'form-control col-5','placeholder':'Input your Name'}),
			'description': forms.Textarea(attrs={'class':'form-control col-5','rows':3,'placeholder':'Input your Description'}),
			'majors': forms.Select(attrs={'class':'form-control col-5'})
		}



adminView/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from .models import Hajime
from .forms import PostForm
from django.views.generic.base import TemplateView,RedirectView,View
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import authenticate,login

# Create your views here.
def index(request):
	introduce = Hajime.objects.all()
	error = ''
	form = PostForm(request.POST)
	paginator = Paginator(introduce, 5)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)


	if request.method == 'POST':
		HajimeForm = Hajime(request.POST)

		# Hajime.objects.create(
		# 		name = request.POST.get('name'),
		# 		description = request.POST.get('description'),
		# )
		# if HajimeForm.is_valid():
		# 	post = HajimeForm.save()

		# 	post.save()
		# 	return redirect('adminview:index')
	if request.method == 'POST':

		if form.is_valid():
			form.save()

			return redirect('adminView:index')

		else:
			error = form.errors


	context = {
		'perkenalan': introduce,
		'form' : PostForm,
		'error':error,
		'page_obj':page_obj
	}

	return render(request, 'adminViews/index.html', context)


# class DashboardCreateView(CreateView):
# 	form_class = PostForm
# 	template_name = 'adminViews/index.html'



# def delete(request,id):
# 	Hajime.objects.filter(id=id).delete()
# 	return redirect('adminView:index')

# def update(request,id):
# 	introduce = Hajime.objects.all()
# 	data_db = Hajime.objects.get(id=id)
# 	data = {
# 		'name': data_db.name,
# 		'description': data_db.description,
# 		'majors': data_db.majors
# 	}
# 	error = ''
# 	form = PostForm(request.POST or None, initial=data, instance=data_db)

# 	if request.method == 'POST':
# 		if form.is_valid():
# 			form.save()

# 			return redirect('adminView:index')
			

# 		else: 
# 			error = form.errors


# 	context = {
# 		'perkenalan': introduce,
# 		'forms' : form,
# 		'error':error,
# 	}


# 	return render(request, 'adminViews/index.html', context)

# class IndexViewClass(View):
# 	introduce = Hajime.objects.all()
# 	form = PostForm()
# 	template_name = 'adminViews/index.html'

# 	def get(self,request):
# 		context = {
# 			'perkenalan': self.introduce,
# 			'forms': self.form
# 		}
# 		return render(request, 'adminViews/index.html', context)

# 	def post(self,request):
# 		form = PostForm(request.POST or None)

# 		if request.method == 'POST':
# 			if form.is_valid():
# 				form.save()
				
# 				return redirect('adminView:index')


# 		context = {
# 			'perkenalan': self.introduce,
# 			'form': form
# 		}
# 		return render(request, self.template_name, context)

# class DashboardView(ListView):
# 	template_name = 'adminViews/index.html'
# 	model = Hajime
# 	extra_context = {
# 		'forms': PostForm(),
# 	}
# 	paginate_by = 5
# 	def get_context_data(self, *args, **kwargs):
# 		self.kwargs.update(self.extra_context)
# 		kwargs = self.kwargs
# 		return super().get_context_data()
	# template_name = 'adminViews/index.html'
	# context = {}
	# form = None
	# introduce = Hajime.objects.all()

	# def get(self, *args, **kwargs):
	# 	self.context = {
	# 		'forms': PostForm(),
	# 		'perkenalan': self.introduce
	# 	}
	# 	return render(self.request, self.template_name, self.context)

	# def post(self, *args, **kwargs):
	# 	self.form = PostForm(self.request.POST or None)
	# 	print(self.request.POST)	

	# 	if self.form.is_valid():
	# 		self.form.save()
	# 		return redirect('adminView:index')


class DashboardDeleteView(RedirectView):
	pattern_name = 'adminView:index'

	def get_redirect_url(self, *args, **kwargs):
		id = kwargs['pk']
		print(id)
		Hajime.objects.filter(id=id).delete()
		return super().get_redirect_url()

# class DashboardCreateAndUpdateView(View):
# 	content = None
# 	form = PostForm()
# 	introduce = Hajime.objects.all()
# 	template_name = 'adminViews/index.html'
# 	context = {}
# 	content = None
# 	paginator = None
# 	page_number = None
# 	page_obj = None

# 	def get(self, *args, **kwargs):
# 		if self.content == 'update':
# 			id = kwargs['id']
# 			formDB = Hajime.objects.get(id=id)
# 			data = formDB.__dict__
# 			self.form = PostForm(initial=data, instance=formDB)
# 			self.paginator = Paginator(self.introduce, 5)
# 			self.page_number = self.request.GET.get('page')
# 			self.page_obj = self.paginator.get_page(self.page_number)

# 		self.context = {
# 			'forms' : self.form,
# 			'page_obj': self.page_obj
# 		}
# 		return render(self.request, self.template_name, self.context)

# 	def post(self, *args, **kwargs):
# 		if kwargs.__contains__('id'):
# 			id = kwargs['id']
# 			formDB = Hajime.objects.get(id=id)
# 			self.form = PostForm(self.request.POST, instance=formDB)
# 		else:
# 			self.form = PostForm(self.request.POST)

# 		if self.form.is_valid():
# 			self.form.save()


# 		return redirect('adminView:index')

class DashboardUpdateView(UpdateView):
	form_class = PostForm
	model = Hajime
	introduce = Hajime.objects.all()
	template_name = 'adminViews/index.html'
	paginator = None
	page_number = None
	page_obj = None

	def get_context_data(self, *args, **kwargs):
		self.paginator = Paginator(self.introduce, 5)
		self.page_number = self.request.GET.get('page')
		self.page_obj = self.paginator.get_page(self.page_number)

		context = super().get_context_data()
		context['page_obj'] = self.page_obj
		return context

	
# class DashboardDeleteView(DeleteView):
# 	model = Hajime
# 	template_name = 'adminViews/index.html'
# 	success_url = reverse_lazy('adminView:index')


class DashboardDetailView(DetailView):
	template_name = 'adminViews/detail_index.html'
	model = Hajime




adminView/templates/adminViews/detail_index.html
{% extends 'layouts/master.html' %}
{% load static %}

{% block 'title' %}
	Detail View
{% endblock %}

{% block 'content' %}
	<div class="container-fluid">
    <h1 class="h3 mb-4 text-gray-800">Detail View</h1>
    <div class="card" style="width: 18rem;">
  		<div class="card-body">
		    <h5 class="card-title">{{ object.name }}</h5>
		    <h6 class="card-subtitle mb-2 text-muted">Majors: {{ object.majors }}</h6>
		    <p class="card-text">{{ object.description }}</p>
		    <a href="{% url 'adminView:index' %}" class="btn btn-danger btn-medium">Back</a>
	  	</div>
	</div>
	</div>
{% endblock  %}

adminView/templates/adminViews/index.html
{% extends 'layouts/master.html' %}

{% block 'content' %}
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">Hajime Mashite</h1>
    <form method="POST" >
    	{% csrf_token %}
  <div class="form-group">
    <label for="{{ form.name.id_for_label }}">Full Name</label>
    {{ form.name }}
    <!-- <small class="text-danger" >{{ error.name }}</small> -->
    <!-- <input type="text" class="form-control" name="name" id="formGroupExampleInput" placeholder="Full Name"> -->
  </div>
  <div class="form-group">
    <label for="{{ form.description.id_for_label }}">Description</label>
    {{ form.description }}
  </div>
   <div class="form-group">
    <label for="{{ form.majors.id_for_label }}">Majors</label>
    {{ form.majors }}
  </div>
  <button class="btn btn-success mb-2">Kirim</button>
</form>

<table class="table">
  <thead>
    <tr>
      <th scope="col">No</th>
      <th scope="col">Full Name</th>
      <th scope="col">Description</th>
      <th scope="col">Majors</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
      {% for hajime in page_obj %}
    <tr>
		<td>{{ forloop.counter }}</td>
		<td>{{ hajime.name }}</td>
		<td>{{ hajime.description }}</td>
    <td>{{ hajime.majors }}</td>
    <td><a href="{% url 'adminView:index_detail' hajime.id %}" class="btn btn-primary btn-medium">Details</a>
    <a href="{% url 'adminView:index_update' hajime.id %}" class="btn btn-warning btn-medium">Edit</a>
    <a href="{% url 'adminView:index_delete' hajime.id %}" class="btn btn-danger btn-medium">Delete</a>
  
    </td>

    </tr>

      {% endfor %}
</tbody>
</table><br>
{% include 'layouts/pagination.html' %}

 </div>
{% endblock %}
 
        

adminView/templates/adminViews/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Login</title>
</head>
<body>
	<h5>{{ user }}</h5>
	<h1>Login Form</h1>
	<form method="POST">
		{% csrf_token %}
	<label for="username">Username</label>
	<input type="text" name="username" id="username">
	<br>
	<br>
	<label for="password">Password</label>
	<input type="password" name="password" id="password">
	<br>
	<button type="submit">Login</button>
	</form>
	
</body>
</html>

adminView/templates/adminViews/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Logout</title>
</head>
<body>
	<form method="POST">
		{% csrf_token %}
	<h5>do you want to logout?</h5>
	<button type="submit">Yeahh</button>
	</form>
</body>
</html>